FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:22-alpine AS runtime
ENV NODE_ENV=production
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY config ./config
COPY src ./src
COPY package*.json ./
USER node
EXPOSE 3000
CMD ["node", "src/index.js"]
